Layout/LineLength:
  Max: 100

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - lib/ehb_game_lib/globals.rb

Metrics/AbcSize:
  Exclude:
    - lib/ehb_game_lib/gfx.rb

Metrics/MethodLength:
  Exclude:
    - lib/ehb_game_lib/gfx.rb

Metrics/ParameterLists:
  Exclude:
    - lib/ehb_game_lib/patches/gosu/font.rb
