Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - lib/ehb_game_lib/globals.rb

Metrics/LineLength:
  Max: 100

Metrics/ParameterLists:
  Exclude:
    - lib/ehb_game_lib/patches/gosu/font.rb
